### ISSUE TITLE
Unable to view doc

### ISSUE THREAD

**Issue by juhnny5** [YtenSoftware/Nety#14]
Good morning, sir, 

The documentation is no longer accessible... Is the project still current?
Thank you for your return.

Julien.

**Comment by richardstrnad** [comment]
Hi Julien,

The Project ist usable, but we are currently not active developing. Feel free to provide some PRs, we are happy to merge them :-)

If you are looking for a more complete/active project, you can checkout https://github.com/mpenning/CiscoConfParse which was the source for this "fork".

Cheers
Richy

**Comment by richardstrnad** [comment]
Doc is back online, hope this helps :-)
